# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Start from the official Python image (using slim for smaller size)
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy dependency specification files
COPY pyproject.toml uv.lock ./

# Install runtime dependencies
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir httpx mcp[cli]>=1.6.0

# Copy the MCP server script
COPY gaggiuino.py ./

# Default command to run the MCP server over stdio
CMD ["python", "gaggiuino.py"]
